### PR TITLE
TypeScript errors

### PR DESCRIPTION
**Pull request by divergentdave**
This is still a work in progress, but I've been fixing Typescript errors. 13 to go! I'll let you know when this is ready for review.

### CODE REVIEW

**Comment by divergentdave** [comment]
This is ready for review! I get no warnings or errors while building now.

**Comment by gmarty** [comment]
Hey! That's amazing!
I reviewed the code and it looks all good to me.
Can you just squash all commits into a single one? Then I can merge it.

Thanks a million!

**Comment by divergentdave** [comment]
No problem, I'll do that tonight. Happy to help!

**Comment by divergentdave** [comment]
I squashed everything but 4e7a9cf66ded288170852db5c0d708fe65f871af, which was really from #5.

**Comment by gmarty** [comment]
There are conflicts and I can't merge this PR.
Let me have a look at what's wrong.

**Comment by divergentdave** [comment]
Yeah, I'm worried I didn't squash the commits right. There aren't any
differences in the tree of this branch and the tree of the un-squashed
branch, and I think there wasn't any conflict before squashing. I'll take a
look too tonight.

**Comment by divergentdave** [comment]
There, this should work now. I added another parent to the commit to reflect an intermediate merge.

**Comment by gmarty** [comment]
This is merged now. Thanks again for your help!

**Pull request merged**
